export type Product = {
  id: number,
  name: string,
  new_price: number,
  old_price: number,
  total: number,
  sold: number,
  description?: string,
  category: string,
  category_link: string,
  series: string,
  series_link: string,
  color: string,
  color_value: string,
  storage: string,
  storage_value: number,
  status: string,
  status_value: number,
};
